### PR TITLE
fix: reversed token expiration and refresh logic

### LINKED ISSUE #199: bug: Token Refresh Logic is Reversed
Sorry if I'm being dumb here, but I was reading through the code to get a better idea of how tokens are stored/used etc and noticed this. If I am reading this right, the function is returning the access token if there is no refresh token or if `tokens.expiresIn` is both truthy (meaning both defined and non-zero) and less than 5.

https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/get_session_access_token.ts#L30-L36

I think there is one main issue with this. If `expiresIn` is a non-zero value that is less than 5, we probably _do_ want to refresh the token right? There are two cases:
1. `expiresIn` is negative, meaning it is already expired and we should refresh
2. `expiresIn` indicates that the token will expire soon (the 5 second buffer mentioned in the comment) and we should refresh

With the current logic, isn't the function basically only refreshing the token if it is not going to expire soon or if `expiresIn` is _exactly_ `0`? Should that `<` actually be a `>`? Or am I crazy

This would definitely be problematic because there would likely be a large number of requests being made to oauth providers and a bunch KV writes that are unnecessary

### PR DESCRIPTION
**Pull request by mitchwadair**
Closes #199 

This PR is on top of #200, so some changes will show up here until that is also merged and I rebase

### Explanation
Currently, the `getSessionAccessToken` function is returning the access token if there is no refresh token or if `tokens.expiresIn` is both truthy (meaning both defined and non-zero) and less than 5.

https://github.com/denoland/deno_kv_oauth/blob/b4007c04c55a840ac8451037e947c63162c0ae60/src/get_session_access_token.ts#L30-L36

The issue with this is that if `expiresIn` is a non-zero value that is less than 5, we actually _do_ want to refresh the token. There are three cases which need to be addressed when it comes to just returning the access token:
1. `refreshToken` is `undefined`
2. `expiresIn` is `undefined`
3. `expiresIn` is greater than `5`

With the current logic, the function is only refreshing the token if it is _not_ going to expire soon or if `expiresIn` is _exactly_ `0`. This will cause problems where a bunch of unnecessary requests get made to OAuth providers and unnecessary writes are made to KV.

There is also one more minor fix here, and that is not multiplying `5` by `SECOND`. `expiresIn` is already a value in seconds, so this made the condition off by a factor of 1000.

### Testing
Previously, tests were passing because of one major flaw: `refreshToken` was never defined, so the test which was checking that tokens were returned with a long expiry was getting a false-positive. I fixed that in test by adding an optional `withRefresh` argument to `genTokens`. This defaults to true.

I also added some additional tests to cover cases that were previously missed:
1. `refreshToken` being `undefined`
2. A token that expires soon, but hasn't expired yet

I also updated the test `returns the access token for session with far expiry` to just have a 30 second expiry instead of an astronomically large number

I also added some `await`s to `assertRejects` that were causing false-passes for the tests using them

### CODE REVIEW

File: src/test_utils.ts
Comment (iuioiua) [inline src/test_utils.ts:1]: I think we can revert this and instead just append the `refreshToken` property where needed.

**Review by iuioiua — CHANGES_REQUESTED** [review]

File: src/test_utils.ts
Comment (mitchwadair) [reply src/test_utils.ts:1]: done 👍

File: src/get_session_access_token_test.ts [hunk 1]
```diff
@@ -32,27 +49,42 @@ Deno.test("getSessionAccessToken()", async (test) => {
...
     const sessionId = crypto.randomUUID();
     const tokens: Tokens = {
       ...genTokens(),
-      expiresIn: 0,
+      refreshToken: crypto.randomUUID(),
+      expiresIn: 3,
     };
     await setTokens(sessionId, tokens);
-    assertRejects(async () =>
+    await assertRejects(async () =>
```
Comment (mitchwadair) [inline src/get_session_access_token_test.ts:60]: I also found that the `assertRejects` calls were not awaited and were causing false-positives in test as well

File: src/get_session_access_token_test.ts [hunk 2]
```diff
@@ -32,27 +49,42 @@ Deno.test("getSessionAccessToken()", async (test) => {
...
+  //   const tokens: Tokens = {
+  //     ...genTokens(),
+  //     refreshToken: crypto.randomUUID(),
+  //     expiresIn: 60,
+  //   };
+  //   await setTokens(sessionId, tokens);
+  //   await assertRejects(async () =>
+  //     await getSessionAccessToken(oauth2Client, sessionId)
+  //   );
+  // });
```
Comment (mitchwadair) [inline src/get_session_access_token_test.ts:89]: After adding the `await` to `assertRejects` here, the test fails because correct conditions are met to just return the token. Is there something specific this is supposed to be testing? I can't tell if there is really a way to test what the descriptions says it is testing. I'm not really sure this one makes sense to include

Comment (iuioiua) [reply src/get_session_access_token_test.ts:89]: Can you please open an issue? Let's tackle this separately.

Comment (mitchwadair) [reply src/get_session_access_token_test.ts:89]: Should I leave it commented or remove the `await` in the meantime?

Comment (iuioiua) [reply src/get_session_access_token_test.ts:89]: Let's completely revert this block as to keep the diff quiet.

File: src/get_session_access_token_test.ts [hunk 3]
```diff
@@ -9,9 +9,25 @@ Deno.test("getSessionAccessToken()", async (test) => {
     assertEquals(await getSessionAccessToken(oauth2Client, "nil"), null);
   });
 
+  await test.step("returns the access token for session without refresh token", async () => {
+    const sessionId = crypto.randomUUID();
+    const tokens = {
+      ...genTokens(),
+      expiresIn: 3, // if we had a refresh token this would cause a refresh
```
Comment (iuioiua) [inline src/get_session_access_token_test.ts:16]: Nice

File: src/get_session_access_token_test.ts [hunk 4]
```diff
@@ -1,6 +1,6 @@
 // Copyright 2023 the Deno authors. All rights reserved. MIT license.
 import { getSessionAccessToken } from "./get_session_access_token.ts";
-import { assertEquals, assertRejects, SECOND, Tokens } from "../dev_deps.ts";
+import { assertEquals, assertRejects, Tokens } from "../dev_deps.ts";
```
Comment (iuioiua) [inline src/get_session_access_token_test.ts:3]:
```suggestion
import { assertEquals, assertRejects, type Tokens } from "../dev_deps.ts";
```
Nit

File: src/get_session_access_token_test.ts [hunk 5]
```diff
@@ -9,9 +9,25 @@ Deno.test("getSessionAccessToken()", async (test) => {
     assertEquals(await getSessionAccessToken(oauth2Client, "nil"), null);
   });
 
+  await test.step("returns the access token for session without refresh token", async () => {
+    const sessionId = crypto.randomUUID();
+    const tokens = {
```
Comment (iuioiua) [inline src/get_session_access_token_test.ts:14]:
```suggestion
    const tokens: Tokens = {
```
Nit

**Review by iuioiua — CHANGES_REQUESTED** [review]

**Review by iuioiua — APPROVED** [review]
LGTM! Great work. Thank you, Mitch.

**Comment by mitchwadair** [comment]
Happy to help! Thanks for the feedback 👍
